# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3324001d6f5fff053733017e1f69be29b95cd4a3148285ca2e6f4c3511bb854addd2309a06d4663d5c1550dbfdd8a386bf9aaf7f5df2f01046cf0372806c5c78

test:
  secret_key_base: 1d348132746c2d3fc1b65eb842a3c25a79baaa0c8537871d293e2940e7a15994b79c39bfac0223d963b14f27cbebbcb06b048cdbf78dc18b17cb027a5070d469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
