module AuthicClient
  # Authic config
  AUTHIC_CLIENT_KEY ||= ENV['AUTHIC_CLIENT_KEY'] ||= 'NOF6n6yJ97cvEaAeQ7wTUTRZ8znoVcJg8ccjL7Zc'  
  AUTHIC_CLIENT_SECRET ||= ENV['AUTHIC_CLIENT_SECRET'] ||= 'A65EzldzAgZnA5qdDoYUP8FUEICTVXfAAUITVbw3'  
  AUTHIC_CLIENT_SUBDOMAIN ||= ENV['AUTHIC_CLIENT_SUBDOMAIN'] ||= 'testapp'
end