module AuthicClient
  # Authic config
  AUTHIC_CLIENT_KEY ||= ENV['AUTHIC_CLIENT_KEY'] ||= 'E6FRBHNNhWDOMhubF9hfg4ibhuiHn4XMngkbXl5o'  
  AUTHIC_CLIENT_SECRET ||= ENV['AUTHIC_CLIENT_SECRET'] ||= 'YjpvSh7KqjnpTfhZgklBQqrpFRamz7354t9GzPoj'  
  AUTHIC_CLIENT_SUBDOMAIN ||= ENV['AUTHIC_CLIENT_SUBDOMAIN'] ||= 'dev'
end